# Generated by Django 2.2.5 on 2019-10-28 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
