# Generated by Django 2.2.5 on 2019-10-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_replymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='replymodel',
            name='replyToInt',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
